import json
import sys
from pathlib import Path
from types import SimpleNamespace

from langchain_core.messages import HumanMessage

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from agents.workers import travel_worker
from agents.workers.budget_worker import budget_node
from agents.workers.travel_worker import (
    itinerary_node,
    sanitize_itinerary_result,
    validate_itinerary_result,
)


def make_state(**overrides):
    state = {
        "messages": [HumanMessage(content="請安排台中兩天一夜行程")],
        "user_query": "請安排台中兩天一夜行程",
        "destination": "台中",
        "days": 2,
        "nights": 1,
        "total_budget": 6000,
        "spot_result": {},
        "traffic_result": {"total_transport_cost": 500},
        "transport_result": {"total_transport_cost": 500},
        "booking_result": {},
        "budget_allocation": {
            "hotel_budget": 2400,
            "transport_budget": 1080,
            "food_budget": 1620,
            "activity_budget": 300,
            "buffer_budget": 600,
        },
    }
    state.update(overrides)
    return state


def itinerary_with_items(items):
    return {
        "destination": "台中",
        "days": 1,
        "schedule": [{"day": 1, "items": items}],
        "ticket_cost_total": 9999,
        "source": "llm",
        "model": "fake-model",
        "source_detail": "Generated by AI Itinerary Agent.",
    }


def test_invalid_taichung_place_falls_back(monkeypatch):
    invalid = itinerary_with_items([
        {"place": "清水斷崖", "activity": "健行", "type": "outdoor", "estimated_cost": 0}
    ])
    is_valid, reason = validate_itinerary_result(invalid, make_state())
    assert not is_valid
    assert "清水斷崖" in reason

    class FakeChatOpenAI:
        def __init__(self, **kwargs):
            pass

        def invoke(self, messages):
            return SimpleNamespace(content=json.dumps(invalid, ensure_ascii=False))

    monkeypatch.setattr(travel_worker, "ChatOpenAI", FakeChatOpenAI)
    result = itinerary_node(make_state())

    assert result["itinerary_result"]["source"] == "mock_fallback"
    assert result["itinerary_result"]["validation_status"] == "fallback"
    assert "清水斷崖" in result["itinerary_result"]["validation_notes"][0]


def test_hotel_item_is_invalid_or_removed():
    itinerary = itinerary_with_items([
        {"place": "台中市中心飯店", "activity": "住宿選擇", "type": "hotel", "estimated_cost": 2100},
        {"place": "草悟道", "activity": "散步", "type": "outdoor", "estimated_cost": 0},
    ])
    is_valid, _ = validate_itinerary_result(itinerary, make_state())
    sanitized = sanitize_itinerary_result(itinerary, make_state())

    assert not is_valid
    assert [item["place"] for item in sanitized["schedule"][0]["items"]] == ["草悟道"]


def test_transport_food_cost_not_counted():
    itinerary = itinerary_with_items([
        {"place": "台中車站", "activity": "搭車", "type": "transport", "estimated_cost": 700},
        {"place": "餐廳", "activity": "午餐", "type": "food", "estimated_cost": 300},
        {"place": "國家歌劇院", "activity": "參觀", "type": "outdoor", "estimated_cost": 100},
    ])

    sanitized = sanitize_itinerary_result(itinerary, make_state())

    assert sanitized["ticket_cost_total"] == 100
    assert [item["estimated_cost"] for item in sanitized["schedule"][0]["items"]] == [0, 0, 100]


def test_llm_valid_itinerary_keeps_source_llm():
    itinerary = itinerary_with_items([
        {"place": "審計新村", "activity": "散步", "type": "outdoor", "estimated_cost": 0}
    ])

    sanitized = sanitize_itinerary_result(itinerary, make_state())

    assert sanitized["source"] == "llm"
    assert sanitized["validation_status"] == "sanitized"


def test_budget_uses_sanitized_ticket_cost():
    itinerary = itinerary_with_items([
        {"place": "台中車站", "activity": "搭車", "type": "transport", "estimated_cost": 700},
        {"place": "餐廳", "activity": "午餐", "type": "food", "estimated_cost": 300},
        {"place": "展覽館", "activity": "特展", "type": "indoor", "estimated_cost": 100},
    ])
    sanitized = sanitize_itinerary_result(itinerary, make_state())

    result = budget_node(make_state(itinerary_result=sanitized))

    assert result["budget_result"]["breakdown"]["activity"] == 100
